# ! Important
# Since we rely in our code to environment variables for e.g. db connection
# this can only be run successfully with docker-compose file

# Specify node version and choose image
# also name our image as development (can be anything)
FROM node:19-bullseye-slim as base

RUN npm i -g pnpm

# Specify our working directory, this is in our container/in our image
WORKDIR /app
# Copy the package.jsons from host to container
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY .npmrc ./
COPY tsconfig.json ./
RUN pnpm install 

COPY . .

CMD npm run dev